{
  "Uuid": "bdaf8f11-89b6-4e6c-82cf-01b2268c03b2",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Element.MoveElement",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "6b013329-a296-4f87-97e6-6d4d326b966e-000d9e1b"
      ],
      "Id": "92ffdca8f5c7464e99d52b4cf32749fd",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2fb657b0f15d4760baed2537ef3a3f7f",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "OpenMEP.Element.Element.MoveElement@Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point",
      "Id": "97f3e3f104004022adc1480f54ce4dfb",
      "Inputs": [
        {
          "Id": "2cdd0647476f476ebb5e23ba9ec5790a",
          "Name": "element",
          "Description": "element to move\n\nElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e24bb63d71564ad591d7668b448ae5c5",
          "Name": "newLocation",
          "Description": "translate\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "49aacb9246c54a89a5988776b357a384",
          "Name": "element",
          "Description": "family instance",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Move element to new location\n\nElement.MoveElement (element: Element, newLocation: Point): Element"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "0b4dd0cb7add4ccf881e00a6d58d3d95",
      "Inputs": [
        {
          "Id": "cfbb6fb22ddb4bb2a4ac300cff3aa9cf",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c1ded88075dc4205890a8274c4e004ac",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0139d02a56a748aa98b202bab4ced46e",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b33218a594934fcdb5c947f77346f535",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "2fb657b0f15d4760baed2537ef3a3f7f",
      "End": "2cdd0647476f476ebb5e23ba9ec5790a",
      "Id": "5e0cba2fd80149a29315aaf75c2f97aa",
      "IsHidden": "False"
    },
    {
      "Start": "b33218a594934fcdb5c947f77346f535",
      "End": "e24bb63d71564ad591d7668b448ae5c5",
      "Id": "cdc69650061a4f5eb73eee08473b09ad",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "97f3e3f104004022adc1480f54ce4dfb"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.16",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "3.0",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.1.2727",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -60287.8984375,
      "EyeY": 3992.359619140625,
      "EyeZ": -22583.439453125,
      "LookX": 16.2890625,
      "LookY": -9.672607421875,
      "LookZ": 20.314453125,
      "UpX": 0.087078094482421875,
      "UpY": 0.99026799201965332,
      "UpZ": 0.10856648534536362
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Select Model Element",
        "ShowGeometry": true,
        "Id": "92ffdca8f5c7464e99d52b4cf32749fd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 349.62678185745142,
        "Y": 357.86177105831518
      },
      {
        "Name": "Element.MoveElement",
        "ShowGeometry": true,
        "Id": "97f3e3f104004022adc1480f54ce4dfb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 744.73531767044426,
        "Y": 362.89818934572713
      },
      {
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Id": "0b4dd0cb7add4ccf881e00a6d58d3d95",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 367.50087216573434,
        "Y": 516.4574710333261
      }
    ],
    "Annotations": [],
    "X": -53.252190600777794,
    "Y": -1.6083311139828993,
    "Zoom": 0.80332159346259768
  }
}