{
  "Uuid": "712c951e-7674-4c1a-8299-cebe956a660f",
  "IsCustomNode": false,
  "Description": "",
  "Name": "MEPCurveType.Shape",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "cf861f32-eaa5-4e67-885f-4c918314a895-00062aed"
      ],
      "Id": "e0ebb668225f448787851cb671eb923b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "296a0e69e3444d2390fba5a97d9bf00c",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.ElementType",
      "Id": "7b7033f652a1490c85a432768b62f86b",
      "Inputs": [
        {
          "Id": "aa95de32d26546cda3eca44e85b894da",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "60f49a53fc0e4a5a9a39bfaffd0b7c00",
          "Name": "ElementType",
          "Description": "Element Type or Null.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the ElementType for this Element. Returns null if the Element cannot have an ElementType assigned.\n\nElement.ElementType: ElementType"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "OpenMEP.Element.MEPCurveType.Shape@Revit.Elements.Element",
      "Id": "1d1d70dcf9784fee844ce9e4b8b4ee13",
      "Inputs": [
        {
          "Id": "fae7db45bee546aea6b4df7fa8d6bd47",
          "Name": "mepcurvetype",
          "Description": "Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7ca5fb8e8c2e4ee2a4a5e909e963aeed",
          "Name": "Autodesk.Revit.DB.ConnectorProfileType",
          "Description": "ConnectorProfileType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The shape of the profile.\n\nMEPCurveType.Shape (mepcurvetype: Element): var[]..[]"
    }
  ],
  "Connectors": [
    {
      "Start": "296a0e69e3444d2390fba5a97d9bf00c",
      "End": "aa95de32d26546cda3eca44e85b894da",
      "Id": "410b366bee0d4e85ab0757eaf36b3ddb",
      "IsHidden": "False"
    },
    {
      "Start": "60f49a53fc0e4a5a9a39bfaffd0b7c00",
      "End": "fae7db45bee546aea6b4df7fa8d6bd47",
      "Id": "6ff12b8ae3e547fb9145e05cd5642836",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "1d1d70dcf9784fee844ce9e4b8b4ee13"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.16",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "3.0",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.1.2727",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Select Model Element",
        "ShowGeometry": true,
        "Id": "e0ebb668225f448787851cb671eb923b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 180.94198642781271,
        "Y": 60.852436515976621
      },
      {
        "Name": "Element.ElementType",
        "ShowGeometry": true,
        "Id": "7b7033f652a1490c85a432768b62f86b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 486.99485834995937,
        "Y": 84.055256046480054
      },
      {
        "Name": "MEPCurveType.Shape",
        "ShowGeometry": true,
        "Id": "1d1d70dcf9784fee844ce9e4b8b4ee13",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 805.4842720737438,
        "Y": 108.26058516661425
      }
    ],
    "Annotations": [],
    "X": -85.47414521946439,
    "Y": 252.68033317617244,
    "Zoom": 0.76152673577534391
  }
}