{
  "Uuid": "712c951e-7674-4c1a-8299-cebe956a660f",
  "IsCustomNode": false,
  "Description": "",
  "Name": "MEPCurve.BreakCurve",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "f1e12091-0c8a-4299-b9fe-a6a59d270813-000d9e02"
      ],
      "Id": "e0ebb668225f448787851cb671eb923b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "296a0e69e3444d2390fba5a97d9bf00c",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "OpenMEP.Element.MEPCurve.BreakCurve@Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point",
      "Id": "f6f4ab67d08043dba5c1da8531c55c68",
      "Inputs": [
        {
          "Id": "0184da9d4a674a6e8ee26216011bb8f6",
          "Name": "mepCurve",
          "Description": "A curve object for duct or pipe blend elements.\n\nElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8292373a1819403a87be251521616be9",
          "Name": "point",
          "Description": "location to break on mep curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cae00049db564501a715a5da05800147",
          "Name": "element",
          "Description": "new element break from mep curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "break mep curve at point\n\nMEPCurve.BreakCurve (mepCurve: Element, point: Point): Element"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "25501b0f660444e9ad17d67947ede520",
      "Inputs": [
        {
          "Id": "eabe13c1a2894a84a2e6a9964e97c2fd",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3280ca3339604ca99ab4ca65c2f698c9",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "85d419c963984dad8f870b81a0f12a0b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.GetLocation",
      "Id": "2954ad07173c4a64ae44bbe1f0d3d77c",
      "Inputs": [
        {
          "Id": "4cf08b6f56964a9eba523da3687d007c",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8200f1161ba2455490f85e58fdd725c9",
          "Name": "Geometry",
          "Description": "Location Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get an existing element's location\n\nElement.GetLocation ( ): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "e8bbe224ea9c46b98d0ed6e7d08e4bc4",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "17ec1d63ff0d43d98b1310b796017414",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "296a0e69e3444d2390fba5a97d9bf00c",
      "End": "0184da9d4a674a6e8ee26216011bb8f6",
      "Id": "4e79ce5e165746da91124c45f479d72f",
      "IsHidden": "False"
    },
    {
      "Start": "296a0e69e3444d2390fba5a97d9bf00c",
      "End": "4cf08b6f56964a9eba523da3687d007c",
      "Id": "2448faea9e41483b81203c7a3bec40b6",
      "IsHidden": "False"
    },
    {
      "Start": "85d419c963984dad8f870b81a0f12a0b",
      "End": "8292373a1819403a87be251521616be9",
      "Id": "8be071c91db5473a996cf3d4022e0f26",
      "IsHidden": "False"
    },
    {
      "Start": "8200f1161ba2455490f85e58fdd725c9",
      "End": "eabe13c1a2894a84a2e6a9964e97c2fd",
      "Id": "ac216ac1d4c5487ab3e8e167986fec32",
      "IsHidden": "False"
    },
    {
      "Start": "17ec1d63ff0d43d98b1310b796017414",
      "End": "3280ca3339604ca99ab4ca65c2f698c9",
      "Id": "77e1177cc58e4909bec8b578b44eff42",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "f6f4ab67d08043dba5c1da8531c55c68"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.16",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "3.0",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.1.2727",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Select Model Element",
        "ShowGeometry": true,
        "Id": "e0ebb668225f448787851cb671eb923b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 237.73768545994085,
        "Y": 103.66765578635014
      },
      {
        "Name": "MEPCurve.BreakCurve",
        "ShowGeometry": true,
        "Id": "f6f4ab67d08043dba5c1da8531c55c68",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 893.07400281624086,
        "Y": 190.20994707004843
      },
      {
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Id": "25501b0f660444e9ad17d67947ede520",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 588.3037430561958,
        "Y": 258.56082507568425
      },
      {
        "Name": "Element.GetLocation",
        "ShowGeometry": true,
        "Id": "2954ad07173c4a64ae44bbe1f0d3d77c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 506.1319999148493,
        "Y": 77.022619736154837
      },
      {
        "Name": "Code Block",
        "ShowGeometry": true,
        "Id": "e8bbe224ea9c46b98d0ed6e7d08e4bc4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 258.0,
        "Y": 370.0
      }
    ],
    "Annotations": [],
    "X": -174.59017691386509,
    "Y": 93.728413650483276,
    "Zoom": 0.91556228528122652
  }
}