{
  "Uuid": "ea9666a5-3648-46cd-9fdd-710e8831ef9c",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Curve.SplitBySegmentsLengths",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "dcd0f3dba40d4f84bfb002b05e394628",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c85166b8db444df79eec86a2cb02afda",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8dcab9cdb7214a6e87477d096d911d4b",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ec086f3ae31b4b32859a89f56af5a756",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "8befb83a9c22429ca247996072c9c30e",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "602465e85be64e72a5d976b071e1f955",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2c60c8537ec24035ae5a3aae4c4f41cd",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "Autodesk.Point.ByCoordinates(0,0,0);\nAutodesk.Point.ByCoordinates(100,0,0);"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "605d9a69c60c408785543c61735dd14f",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "42d2e4e1311a46d5a815c9bf25a634d7",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "[20,30];"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "ef54442588a046c3adeced66a21594b1",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "453b9129a79c4beb8c9569204466e809",
          "Name": "curve",
          "Description": "The input curve to be split.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7918cae3ebc74b1fbef741924b3b6a92",
          "Name": "segmentLengths",
          "Description": "A list of numbers that represent the lengths of the segments to split the curve into.\n\ndouble[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1093389082cf40feb565ba02721f1ddf",
          "Name": "Curve[]",
          "Description": "A list of curves that result from splitting the input curve at the specified segment lengths. The list includes the original curve and the newly created segments.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Curve.SplitBySegmentsLengths@Autodesk.DesignScript.Geometry.Curve,double[]",
      "Replication": "Auto",
      "Description": "splits a curve into segments of varying lengths specified by a list of segment lengths\n\nCurve.SplitBySegmentsLengths (curve: Curve, segmentLengths: double[]): Curve[]"
    }
  ],
  "Connectors": [
    {
      "Start": "ec086f3ae31b4b32859a89f56af5a756",
      "End": "453b9129a79c4beb8c9569204466e809",
      "Id": "072dc23b13b94185af50e758210dc7cb",
      "IsHidden": "False"
    },
    {
      "Start": "602465e85be64e72a5d976b071e1f955",
      "End": "c85166b8db444df79eec86a2cb02afda",
      "Id": "23aff50ea4d642c0ad2ad1a2713f3dac",
      "IsHidden": "False"
    },
    {
      "Start": "2c60c8537ec24035ae5a3aae4c4f41cd",
      "End": "8dcab9cdb7214a6e87477d096d911d4b",
      "Id": "42a4a64d511f4fe18c8d7b0cd60c3272",
      "IsHidden": "False"
    },
    {
      "Start": "42d2e4e1311a46d5a815c9bf25a634d7",
      "End": "7918cae3ebc74b1fbef741924b3b6a92",
      "Id": "c823ff73804f476e8ea0cad251342f9e",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "ef54442588a046c3adeced66a21594b1"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -31.445751190185547,
      "EyeY": 152.2044677734375,
      "EyeZ": 238.4566650390625,
      "LookX": 102.42955780029297,
      "LookY": -149.7088623046875,
      "LookZ": -216.79536437988281,
      "UpX": 0.14330178499221802,
      "UpY": 0.94205731153488159,
      "UpZ": -0.30330276489257813
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "dcd0f3dba40d4f84bfb002b05e394628",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 210.313209328394,
        "Y": 247.31339057409735
      },
      {
        "Id": "8befb83a9c22429ca247996072c9c30e",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -241.63462917316929,
        "Y": 256.08380586719136
      },
      {
        "Id": "605d9a69c60c408785543c61735dd14f",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 316.23426227767482,
        "Y": 420.30935939229346
      },
      {
        "Id": "ef54442588a046c3adeced66a21594b1",
        "Name": "Curve.SplitBySegmentsLengths",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 578.85761895417193,
        "Y": 306.27495191601054
      }
    ],
    "Annotations": [],
    "X": 222.97493322706816,
    "Y": -25.494081384836875,
    "Zoom": 0.93830215564919306
  }
}