{
  "Uuid": "dfb6e896-5fc5-46b5-a2af-5b13d8f6d765",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Line.TopPoint",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "a95b7aaad856439197d6ba003297466d",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "2a7dc9c93ab34ec1b31c6754b0393ce8",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5002c9480ce74274a5dbb603d861ef68",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c98c65a19fb04cef9e6f61bc2aa57c9f",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "91d0992260b04a10acece2df38e1d8da",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "fb8f19269de741b9ab09220988dbba4c",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b2e71f2e3c6f4b32bf826dc46b67451e",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2b3bfcf1fbb6464089d5252396d26700",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "aeee9fac87694040aefc82f1b8f3f417",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "9a89e8f63b9f4e2eb8a5502fe0233735",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c9718f407559421eaadca173251a292d",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "daf98ff802304fba9390a4dc75d13d85",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6279da08941841d6983fc3bf0466d789",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "24ffe5d3847a41ce8e72a66108167a19",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "bd9f5e91a7894103ac19aa61708e7aeb",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "41d7755da0ed46f99402bb0c142fff5e",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "10;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "4ca0f1702f3c467d93393335bc33774f",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "66fe4abecab24d70b2b4ec18694c4a16",
          "Name": "line",
          "Description": "the line to get\n\nLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "be06c6777dc64c649b2930fcbe24dff9",
          "Name": "point",
          "Description": "top point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Line.TopPoint@Autodesk.DesignScript.Geometry.Line",
      "Replication": "Auto",
      "Description": "get top point of line\n\nLine.TopPoint (line: Line): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "c98c65a19fb04cef9e6f61bc2aa57c9f",
      "End": "66fe4abecab24d70b2b4ec18694c4a16",
      "Id": "9481c0889c9343b9b225f776f45cb92a",
      "IsHidden": "False"
    },
    {
      "Start": "aeee9fac87694040aefc82f1b8f3f417",
      "End": "2a7dc9c93ab34ec1b31c6754b0393ce8",
      "Id": "a66bbc24cf794471adc03de772cf3b44",
      "IsHidden": "False"
    },
    {
      "Start": "24ffe5d3847a41ce8e72a66108167a19",
      "End": "5002c9480ce74274a5dbb603d861ef68",
      "Id": "1ffe2bad386145cf8e0e87fcabb2386a",
      "IsHidden": "False"
    },
    {
      "Start": "41d7755da0ed46f99402bb0c142fff5e",
      "End": "c9718f407559421eaadca173251a292d",
      "Id": "328a9b8d5d0e40019b589ae7677f1b4d",
      "IsHidden": "False"
    },
    {
      "Start": "41d7755da0ed46f99402bb0c142fff5e",
      "End": "daf98ff802304fba9390a4dc75d13d85",
      "Id": "f24c7f5ebdce4c23a0b7327f0461b7b6",
      "IsHidden": "False"
    },
    {
      "Start": "41d7755da0ed46f99402bb0c142fff5e",
      "End": "6279da08941841d6983fc3bf0466d789",
      "Id": "9184af05e289432eba2af27e4f67adc1",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "4ca0f1702f3c467d93393335bc33774f"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "a95b7aaad856439197d6ba003297466d",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 541.6,
        "Y": 320.80000000000007
      },
      {
        "Id": "91d0992260b04a10acece2df38e1d8da",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 179.20000000000005,
        "Y": 183.2
      },
      {
        "Id": "9a89e8f63b9f4e2eb8a5502fe0233735",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 216.80000000000007,
        "Y": 411.2
      },
      {
        "Id": "bd9f5e91a7894103ac19aa61708e7aeb",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -12.0,
        "Y": 469.0
      },
      {
        "Id": "4ca0f1702f3c467d93393335bc33774f",
        "Name": "Line.TopPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 904.00865252302083,
        "Y": 228.07678758882923
      }
    ],
    "Annotations": [],
    "X": 228.76458608355904,
    "Y": 34.235128132697184,
    "Zoom": 0.82770257044119022
  }
}