{
  "Uuid": "41f2b803-f361-4d15-9fc5-2cef5d814afb",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Line.Slope",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "b14e0b0261c7474db79065e0d7746b87",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "3586546c49c149309035918db8b50865",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5f2bba4a20b5415e9a7bcca5bf527fed",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "36a7f73bc3ec44fbbea05c1437234618",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "9dc0e434199d4459bd984368113d3539",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "e6fe81c1a36544bb9cacf1e698c18df3",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fa456eb4828e4540b61c4b9e41ca5c1a",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4b87bb95d26643f9b3020e77bee16819",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "910f68be2abe45aba0d58e2961e02798",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "eaea6093d78a4c7191fabe2ad703d4b6",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "12d8674da12048f58ad156b49b1b49d9",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7b22c9865b914dab8e6b3e576bd8fe17",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "93981cb23bdc4eada9b9c431cd237050",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "00586fdfc3274a9a8c18059f7fe3e148",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "785e50e6052748e6b21982576235bcc4",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1bc718a0c4c04ed6ab6f1758ab81fdc5",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "10;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "8f88c4d5a6b64defad1646303995b017",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "23da5cf72e584a9d9e3cd6cafbdab846",
          "Name": "line",
          "Description": "line to get slope\n\nLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "93b969ee7bc042388b77eb4a2fa5d81b",
          "Name": "digits",
          "Description": "The number of fractional digits in the return value.\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "741afaab0bcc4346b84ce62a808851c3",
          "Name": "slope",
          "Description": "value slope of line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Line.Slope@Autodesk.DesignScript.Geometry.Line,double",
      "Replication": "Auto",
      "Description": "Return slope of line\n\nLine.Slope (line: Line, digits: double = 0): double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "a5b62151600f4aa68c6b45986cb44dcc",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "00446424da6546d6adc1786d4891e58d",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "3;"
    }
  ],
  "Connectors": [
    {
      "Start": "36a7f73bc3ec44fbbea05c1437234618",
      "End": "23da5cf72e584a9d9e3cd6cafbdab846",
      "Id": "2b573189f58b40feac53ac1c99146a0f",
      "IsHidden": "False"
    },
    {
      "Start": "910f68be2abe45aba0d58e2961e02798",
      "End": "3586546c49c149309035918db8b50865",
      "Id": "e970ad4c8a774924a9ef5531fdedf3f9",
      "IsHidden": "False"
    },
    {
      "Start": "00586fdfc3274a9a8c18059f7fe3e148",
      "End": "5f2bba4a20b5415e9a7bcca5bf527fed",
      "Id": "be8fde0262664daeb0ae2dc1297406c1",
      "IsHidden": "False"
    },
    {
      "Start": "1bc718a0c4c04ed6ab6f1758ab81fdc5",
      "End": "12d8674da12048f58ad156b49b1b49d9",
      "Id": "d2d9afee6a8f44209217a24bee104ae5",
      "IsHidden": "False"
    },
    {
      "Start": "1bc718a0c4c04ed6ab6f1758ab81fdc5",
      "End": "7b22c9865b914dab8e6b3e576bd8fe17",
      "Id": "06322e6c3e9a4be1b46affbfb9aa16a4",
      "IsHidden": "False"
    },
    {
      "Start": "1bc718a0c4c04ed6ab6f1758ab81fdc5",
      "End": "93981cb23bdc4eada9b9c431cd237050",
      "Id": "5d0d8abfba814437a7e2ed025ffd2306",
      "IsHidden": "False"
    },
    {
      "Start": "00446424da6546d6adc1786d4891e58d",
      "End": "93b969ee7bc042388b77eb4a2fa5d81b",
      "Id": "9eaee001965c4381b55d2d08d66dfda5",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "8f88c4d5a6b64defad1646303995b017"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "b14e0b0261c7474db79065e0d7746b87",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 541.6,
        "Y": 320.80000000000007
      },
      {
        "Id": "9dc0e434199d4459bd984368113d3539",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 179.20000000000005,
        "Y": 183.2
      },
      {
        "Id": "eaea6093d78a4c7191fabe2ad703d4b6",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 216.80000000000007,
        "Y": 411.2
      },
      {
        "Id": "785e50e6052748e6b21982576235bcc4",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -12.0,
        "Y": 469.0
      },
      {
        "Id": "8f88c4d5a6b64defad1646303995b017",
        "Name": "Line.Slope",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 880.626116745688,
        "Y": 418.4000000000002
      },
      {
        "Id": "a5b62151600f4aa68c6b45986cb44dcc",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 649.0,
        "Y": 510.59999999999991
      }
    ],
    "Annotations": [],
    "X": -72.795982802389062,
    "Y": -198.69327305281519,
    "Zoom": 1.2777169841077238
  }
}