{
  "Uuid": "3f8b28c5-b474-4b10-bad9-1852390c1f74",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Point.Ceiling",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "39b25d8c31b746f7a69795917574dc16",
      "Inputs": [
        {
          "Id": "a5020742e19545ccbb4b429c63cf34bc",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6cea47a9f57140bf82c87a92f3df93f1",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c9bb4f851eea4a878a0256ef27b7e1f6",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3010723c36104c829f7689c9320d102d",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "35.6;",
      "Id": "b4900b0d8a454e97b1dbee73246f82ae",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "eb09c4dd13484999836e03291a5eb6ef",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "OpenMEPSandbox.Geometry.Point.Ceiling@Autodesk.DesignScript.Geometry.Point",
      "Id": "2e953c231ef04217be0da8d414eb2fce",
      "Inputs": [
        {
          "Id": "cfd69dc72e244a4da2005ccc80024f8c",
          "Name": "point",
          "Description": "The input point.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e9c6bb319bd7482a8284e28d926d780a",
          "Name": "Point",
          "Description": "The point with the larger integer values that are greater than or equal to the X, Y, and Z coordinates of the input point.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns a new point with the larger integer values that are greater than or equal to the X, Y, and Z coordinates of the input point.\n\nPoint.Ceiling (point: Point): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "3010723c36104c829f7689c9320d102d",
      "End": "cfd69dc72e244a4da2005ccc80024f8c",
      "Id": "e33530c13e4341069d7727e8267013df",
      "IsHidden": "False"
    },
    {
      "Start": "eb09c4dd13484999836e03291a5eb6ef",
      "End": "a5020742e19545ccbb4b429c63cf34bc",
      "Id": "172dae160ead4a5cb4234f8242282425",
      "IsHidden": "False"
    },
    {
      "Start": "eb09c4dd13484999836e03291a5eb6ef",
      "End": "6cea47a9f57140bf82c87a92f3df93f1",
      "Id": "7e67d8bf45ee4e1eb7f869b8c58dc391",
      "IsHidden": "False"
    },
    {
      "Start": "eb09c4dd13484999836e03291a5eb6ef",
      "End": "c9bb4f851eea4a878a0256ef27b7e1f6",
      "Id": "813795d77aaa4060a35e81e385ee305a",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "2e953c231ef04217be0da8d414eb2fce"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.17",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.17.2.4543",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Id": "39b25d8c31b746f7a69795917574dc16",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 344.79999999999995,
        "Y": 233.60000000000008
      },
      {
        "Name": "Code Block",
        "ShowGeometry": true,
        "Id": "b4900b0d8a454e97b1dbee73246f82ae",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 108.0,
        "Y": 273.0
      },
      {
        "Name": "Point.Ceiling",
        "ShowGeometry": true,
        "Id": "2e953c231ef04217be0da8d414eb2fce",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 668.11409381885335,
        "Y": 244.85851104489905
      }
    ],
    "Annotations": [],
    "X": -14.640365022321646,
    "Y": -51.902105813002635,
    "Zoom": 1.1047642563030273
  }
}