{
  "Uuid": "f80e1619-d3a0-4b74-b262-c039df3f317a",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Point.ProjectOnToLine",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "fb58d96f314d41b0957902d4529dc6d2",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "92af7bf8857b4073a417ba41d3a94887",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ad7c3da83034411483eb3e12e201bbc1",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2caa27061ce14ff09cf1120c5f47631a",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "2bbaec3d644b42ea90ddc9e311194686",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c4679671e3d94878a0ac51610bec4208",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "aeb760a558e442ce801d37a320ea5830",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a2fff58f8ead4059b284fe074aea621d",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3e2b756b51f44470b66e85980d162241",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "ce065abb4142467b953d15171b1cc82e",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "e410e2e297564f688e2fe1032366cca1",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9559322a16db4aec87f336c78fa2528c",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "403a4f108f224b48aab9fdfec2d00b34",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b11278c47792484c9670230950fad0cd",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "28e4d4ed57a945f2b5cba3a6eb2b9dfc",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ce91fe9170964c4ba4867548745221a2",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "10;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "9260dc9d99e8428d81bf4e7b6522f009",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "42be165bdbef4bafaa93b3abbcf78b40",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "53ea535aa5d445b89fa7a586e65fb7dc",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "02ab209c9f934d8d8ed1a6b5e607d3d2",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2679a135a03c480d94ddc2cd1a527a65",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "65969fa090bb4ed9aa9e21e1ba7c4686",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "516af1cc8da94f04a849424c89f21650",
          "Name": "point",
          "Description": "Point need to project\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8c006946457440b38935e54cc6bdb17e",
          "Name": "line",
          "Description": "Line to project the point\n\nLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "78307685610444fbb014cbac9684fd06",
          "Name": "point",
          "Description": "projected point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Point.ProjectOnToLine@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Line",
      "Replication": "Auto",
      "Description": "Project a point onto a line\n\nPoint.ProjectOnToLine (point: Point, line: Line): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.IntegerSlider, CoreNodeModels",
      "NumberType": "Integer",
      "MaximumValue": 30,
      "MinimumValue": 1,
      "StepValue": 1,
      "Id": "dfa8e3548c3c4715959a2c040f730115",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6b06be05867a430e8009e7c5e303c51e",
          "Name": "",
          "Description": "Int64",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Produces integer values",
      "InputValue": 28
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "8a4ee5fd1b0b4d26ac03dc952e48da2e",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "3b540566a5ba4e38a411a43449f9d96c",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d322540bb52b49599e9811d3c40b5995",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "27f51b1ed5f14ee996cdc176357fd724",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    }
  ],
  "Connectors": [
    {
      "Start": "2caa27061ce14ff09cf1120c5f47631a",
      "End": "8c006946457440b38935e54cc6bdb17e",
      "Id": "93dcb76213864d97b8a718a0c3b9adbf",
      "IsHidden": "False"
    },
    {
      "Start": "3e2b756b51f44470b66e85980d162241",
      "End": "92af7bf8857b4073a417ba41d3a94887",
      "Id": "d48c0dc94aeb4876ab6d05edda28331e",
      "IsHidden": "False"
    },
    {
      "Start": "b11278c47792484c9670230950fad0cd",
      "End": "ad7c3da83034411483eb3e12e201bbc1",
      "Id": "1038a11747404dd69c64d90b04780214",
      "IsHidden": "False"
    },
    {
      "Start": "ce91fe9170964c4ba4867548745221a2",
      "End": "e410e2e297564f688e2fe1032366cca1",
      "Id": "2f4bd4c2a809434cbb13f6ae1facb4ea",
      "IsHidden": "False"
    },
    {
      "Start": "ce91fe9170964c4ba4867548745221a2",
      "End": "403a4f108f224b48aab9fdfec2d00b34",
      "Id": "6aa80aaef8d047fd856961ea2c8fd2f1",
      "IsHidden": "False"
    },
    {
      "Start": "2679a135a03c480d94ddc2cd1a527a65",
      "End": "516af1cc8da94f04a849424c89f21650",
      "Id": "79b289a665d2492ea979900ff50ea66e",
      "IsHidden": "False"
    },
    {
      "Start": "2679a135a03c480d94ddc2cd1a527a65",
      "End": "3b540566a5ba4e38a411a43449f9d96c",
      "Id": "8e27dad6f7884bec8374af4fc2cd17e9",
      "IsHidden": "False"
    },
    {
      "Start": "78307685610444fbb014cbac9684fd06",
      "End": "d322540bb52b49599e9811d3c40b5995",
      "Id": "d7ad559549104d648b9b911641411f22",
      "IsHidden": "False"
    },
    {
      "Start": "6b06be05867a430e8009e7c5e303c51e",
      "End": "53ea535aa5d445b89fa7a586e65fb7dc",
      "Id": "fbc9cb31f33440529a4d385a24c468f0",
      "IsHidden": "False"
    },
    {
      "Start": "6b06be05867a430e8009e7c5e303c51e",
      "End": "42be165bdbef4bafaa93b3abbcf78b40",
      "Id": "b8fa9a64a436492a9d78142a15d823b6",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "65969fa090bb4ed9aa9e21e1ba7c4686"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -30.240104675292969,
      "EyeY": 82.235847473144531,
      "EyeZ": -76.699203491210938,
      "LookX": 41.4981689453125,
      "LookY": -63.968593597412109,
      "LookZ": 86.961479187011719,
      "UpX": 0.15574347972869873,
      "UpY": 0.93232488632202148,
      "UpZ": 0.32636556029319763
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "fb58d96f314d41b0957902d4529dc6d2",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 702.85854271548783,
        "Y": 350.13004188126632
      },
      {
        "Id": "2bbaec3d644b42ea90ddc9e311194686",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 350.79999999999995,
        "Y": 284.0
      },
      {
        "Id": "ce065abb4142467b953d15171b1cc82e",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 338.79999999999995,
        "Y": 532.8
      },
      {
        "Id": "28e4d4ed57a945f2b5cba3a6eb2b9dfc",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 72.3849244848625,
        "Y": 539.04849237206315
      },
      {
        "Id": "9260dc9d99e8428d81bf4e7b6522f009",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 338.0,
        "Y": 808.0
      },
      {
        "Id": "65969fa090bb4ed9aa9e21e1ba7c4686",
        "Name": "Point.ProjectOnToLine",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 757.00116122348538,
        "Y": 694.38850621192751
      },
      {
        "Id": "dfa8e3548c3c4715959a2c040f730115",
        "Name": "Integer Slider",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -319.25670333398091,
        "Y": 859.59693603225412
      },
      {
        "Id": "8a4ee5fd1b0b4d26ac03dc952e48da2e",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1175.2591439946623,
        "Y": 563.56670693401566
      }
    ],
    "Annotations": [],
    "X": 287.14039050993642,
    "Y": -125.8788265463395,
    "Zoom": 0.61610714732743088
  }
}