{
  "Uuid": "be6d3684-e989-41a6-b7ff-db8e311a8556",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Point.ProjectOntoPlane",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "5ca103062a7b4d2a96b409d98de9205a",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "32e9a38014274d94a48d372379c540a1",
          "Name": "point",
          "Description": "point need to project\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b24d4326919f47a1a8b985f191e9ce4e",
          "Name": "plane",
          "Description": "plane to be project\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "291e908c772940de80f87bbb51b77f1d",
          "Name": "point",
          "Description": "new point projected on plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Point.ProjectOntoPlane@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Plane",
      "Replication": "Auto",
      "Description": "Project a point onto a plane\n\nPoint.ProjectOntoPlane (point: Point, plane: Plane): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "1a1013b3c121477eb54370545263e274",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "b42ba31cc58a4c249b92af42c8cbb64c",
          "Name": "origin",
          "Description": "Origin point of plane\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3c629953d5ce44afb561bbe38dcb21fa",
          "Name": "normal",
          "Description": "Normal direction vector of plane\n\nVector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fd3ee420ca9049cfb6b2379c0f291086",
          "Name": "Plane",
          "Description": "Plane created by origin and normal",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "31b6c4ecf51747aa871b6512bb3715c3",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c8ecb1057fd841cc8867f6a7fb599673",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d6659a67941a465dae7d988c0657939d",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d2afbb6214b540f9b298b2b3627685af",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "013a55293e8b4b89bfcb3884d0667850",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.IntegerSlider, CoreNodeModels",
      "NumberType": "Integer",
      "MaximumValue": 100,
      "MinimumValue": 0,
      "StepValue": 1,
      "Id": "f8fe11b241574d9ab93bd28663294195",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "bec293287d3a4b13a70fb50776644f4b",
          "Name": "",
          "Description": "Int64",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Produces integer values",
      "InputValue": 8
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "738c02fa1d2842b4ba5f17bb15a98207",
      "NodeType": "FunctionNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ae2431e62d8949eb9b78b1729d5cd2e3",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.XAxis",
      "Replication": "Auto",
      "Description": "Get the canonical X axis Vector (1,0,0)\n\nVector.XAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "4c7daf830a4a478c8384678b601316a3",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "2d7e4e1715824f0c9e410276a52f8d40",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a5d95aceb070402d910ec3e5d58b5e43",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "526115ea73654afcb0a4cd9470c8435a",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "79fd9f4d9ea44661946968af4da2ff36",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.IntegerSlider, CoreNodeModels",
      "NumberType": "Integer",
      "MaximumValue": 100,
      "MinimumValue": 0,
      "StepValue": 1,
      "Id": "95027c7558f8442096360d64275b6771",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "bbccf804de1d4c7d91af6434db6da284",
          "Name": "",
          "Description": "Int64",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Produces integer values",
      "InputValue": 17
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "6528aacf1cd145948cc3cc225dbe3bff",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "26f1048e075b4b158dabb0c96f7a79e4",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dd17a777630449d6a8fa1ddcd0033f60",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e80fb5cdc13946f7800e98a4990a23c5",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "7ca55658b01549a3bc24c5fffdf54193",
      "NodeType": "FunctionNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "470393ce83284ae5a8c4eb25aad5c8bc",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.YAxis",
      "Replication": "Auto",
      "Description": "Get the canonical Y axis Vector (0,1,0)\n\nVector.YAxis ( ): Vector"
    }
  ],
  "Connectors": [
    {
      "Start": "291e908c772940de80f87bbb51b77f1d",
      "End": "dd17a777630449d6a8fa1ddcd0033f60",
      "Id": "a199c69339f3477d90454d1e74b0b734",
      "IsHidden": "False"
    },
    {
      "Start": "fd3ee420ca9049cfb6b2379c0f291086",
      "End": "b24d4326919f47a1a8b985f191e9ce4e",
      "Id": "968c6558590e427c8f762fc0bbdaa225",
      "IsHidden": "False"
    },
    {
      "Start": "013a55293e8b4b89bfcb3884d0667850",
      "End": "32e9a38014274d94a48d372379c540a1",
      "Id": "6bfe3592a72b4812ba722b7f680f6de0",
      "IsHidden": "False"
    },
    {
      "Start": "013a55293e8b4b89bfcb3884d0667850",
      "End": "26f1048e075b4b158dabb0c96f7a79e4",
      "Id": "aab570264c3e4a309c918208b8799f07",
      "IsHidden": "False"
    },
    {
      "Start": "bec293287d3a4b13a70fb50776644f4b",
      "End": "c8ecb1057fd841cc8867f6a7fb599673",
      "Id": "57dd1b78b3a94aaea179e0ccdaa99d31",
      "IsHidden": "False"
    },
    {
      "Start": "bec293287d3a4b13a70fb50776644f4b",
      "End": "d6659a67941a465dae7d988c0657939d",
      "Id": "89ac6935b3ae402884e48f9f39725225",
      "IsHidden": "False"
    },
    {
      "Start": "ae2431e62d8949eb9b78b1729d5cd2e3",
      "End": "3c629953d5ce44afb561bbe38dcb21fa",
      "Id": "1df0f001eaf54828876fb38b0ad962b0",
      "IsHidden": "False"
    },
    {
      "Start": "79fd9f4d9ea44661946968af4da2ff36",
      "End": "b42ba31cc58a4c249b92af42c8cbb64c",
      "Id": "6cab15a1cd964039aee2d1f03f031edf",
      "IsHidden": "False"
    },
    {
      "Start": "bbccf804de1d4c7d91af6434db6da284",
      "End": "2d7e4e1715824f0c9e410276a52f8d40",
      "Id": "194c79aeeea744328a92466c61ff8d43",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "5ca103062a7b4d2a96b409d98de9205a"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": 26.784555435180664,
      "EyeY": 26.384380340576172,
      "EyeZ": 36.725555419921875,
      "LookX": -15.971466064453125,
      "LookY": -21.730712890625,
      "LookZ": -47.156829833984375,
      "UpX": -0.062308214604854584,
      "UpY": 0.98095512390136719,
      "UpZ": -0.18396934866905212
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "5ca103062a7b4d2a96b409d98de9205a",
        "Name": "Point.ProjectOntoPlane",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 702.0,
        "Y": 351.2
      },
      {
        "Id": "1a1013b3c121477eb54370545263e274",
        "Name": "Plane.ByOriginNormal",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 380.4,
        "Y": 359.19999999999993
      },
      {
        "Id": "31b6c4ecf51747aa871b6512bb3715c3",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 366.0,
        "Y": 156.0
      },
      {
        "Id": "f8fe11b241574d9ab93bd28663294195",
        "Name": "Integer Slider",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -108.0,
        "Y": 217.60000000000008
      },
      {
        "Id": "738c02fa1d2842b4ba5f17bb15a98207",
        "Name": "Vector.XAxis",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 66.839855388007663,
        "Y": 381.28115689594074
      },
      {
        "Id": "4c7daf830a4a478c8384678b601316a3",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 68.800000000000409,
        "Y": 584.00000000000011
      },
      {
        "Id": "95027c7558f8442096360d64275b6771",
        "Name": "Integer Slider",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -355.20000000000005,
        "Y": 592.80000000000007
      },
      {
        "Id": "6528aacf1cd145948cc3cc225dbe3bff",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 976.35065597054154,
        "Y": 186.9259831867767
      },
      {
        "Id": "7ca55658b01549a3bc24c5fffdf54193",
        "Name": "Vector.YAxis",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -128.57663707895517,
        "Y": 421.49309682317863
      }
    ],
    "Annotations": [],
    "X": 313.44002271932789,
    "Y": 73.202471954874227,
    "Zoom": 0.69561644130111489
  }
}